### ISSUE TITLE
Request Context?

### ISSUE THREAD

**Issue by lakshaytalkstomachines** [abdullah-aghayan/user-auth#1]
Why did we not use the context passed onto the function ?

https://github.com/abdullah-aghayan/user-auth/blob/64f7e73f9c5cb8f661c343f31141158558041c30/repository/mongo/repoUser.go#L82

**Comment by abdollah-aghayan** [comment]
In the link bellow you can check why we are using Context.TODO
https://golang.org/pkg/context/#TODO

After I added ctx I forgot to change it to input context(ctx)

**Comment by lakshaytalkstomachines** [comment]
oh okay thankyou, i am just new to go so reading alot of people's code :)

**Comment by abdollah-aghayan** [comment]
No further question!
